### ISSUE TITLE
app-insights az cli extension seems not working properly in AzureChinaCloud (China East 2)

### ISSUE THREAD

**Issue by evanlwj** [Azure/azure-cli-extensions#1092]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
application-insights

### Description of issue (in as much detail as possible)
I have properly logged in with a certain subscription in AzureChinaCloud (China East2)
```
az account show
{
  "environmentName": "AzureChinaCloud",
  "id": "5b5d5f37-8aca-49f8-8682-7ed6d2f00424",
  "isDefault": true,
  "name": "Project Vienna PROD - ChinaEast2",
  "state": "Enabled",
  "tenantId": "a55a4d5b-9241-49b1-b4ff-befa8db00269",
  "user": {
    "name": "oe-wanglongjiang@cme.gbl",
    "type": "user"
  }
}
```
However run any az monitor app-insights command always failed with error "The subscription '5b5d5f37-8aca-49f8-8682-7ed6d2f00424' could not be found" 

for example, api-key show
```
az monitor app-insights api-key show --app model-monitoring-chinaeast2 --resource-group model-mgmt-chinaeast2 --api-key MMSModelMonitoringApiKey
The subscription '5b5d5f37-8aca-49f8-8682-7ed6d2f00424' could not be found.
```

I doubted application-insights is not working in AzureChinaCloud, any insight of it? Appreciate

**Comment by evanlwj** [comment]
Is that possible reason with hard code "**https://api.applicationinsights.io**" in [azext_applicationinsights._client_factory](https://github.com/Azure/azure-cli-extensions/blob/f1f8f52dfe3700845212441912989e9c0d58183c/src/application-insights/azext_applicationinsights/_client_factory.py#L13). 

In AzureChinaCloud, application insights endpoint suffix is **applicationinsights.azure.cn**

**Comment by fengzhou-msft** [comment]
@MyronFanQiu please take a look.

**Comment by MyronFanQiu** [comment]
@alexeldeib Hello. I'm not sure. Does app-insights support AzureChinaCloud?

**Comment by MyronFanQiu** [comment]
@evanlwj Thanks for reporting this. That's maybe the root cause. Currently, for some commands like app-insights or log-analytics, the endpoint is hard coded. I have asked @alexeldeib to confirm this issue and tried to figure out a solution.

**Comment by evanlwj** [comment]
I can confirm application insights is GA'ed in Mooncake, where is able to allow to create application insights instance.

**Comment by alexeldeib** [comment]
Sorry for the slow reply, I've been traveling. The URL for App Insights in AzureChinaCloud is `api.applicationinsights.azure.cn`. We also have `api.loganalytics.azure.cn` for log analytics.

@MyronFanQiu for PowerShell we added the endpoints to the equivalent of this file: https://github.com/Azure/azure-cli/blob/dev/src/azure-cli-core/azure/cli/core/cloud.py#L211-L233 should we do the same here?

**Comment by alexeldeib** [comment]
I think it would be something like this? https://github.com/Azure/azure-cli/pull/11385

**Comment by MyronFanQiu** [comment]
@alexeldeib Thanks. I will take a look in this sprint.

**Comment by MyronFanQiu** [comment]
@evanlwj Hi. We have merged the corresponding PR to add endpoint in ChinaCloud. It will be released in the next week. Could you please install new azure-cli version and have a try?

**Comment by stan-sz** [comment]
I have verified this with the latest Edge builds and the issue still reproes. Evan suggested that this might be because of the hardcoded endpoint in https://github.com/Azure/azure-cli-extensions/blob/f1f8f52dfe3700845212441912989e9c0d58183c/src/application-insights/azext_applicationinsights/_client_factory.py#L13

 that is not leveraging the changes in https://github.com/Azure/azure-cli/pull/11385

**Comment by stan-sz** [comment]
Apart from the above comment about hardcoded app insights, there's also one hard coded: https://github.com/Azure/azure-cli-extensions/blob/cf7cebdbf68cedca9b6bb5c7625d87bc8da819f5/src/application-insights/azext_applicationinsights/vendored_sdks/mgmt_applicationinsights/application_insights_management_client.py#L48

The latter one is the one we are hitting in the repro steps.

**Comment by MyronFanQiu** [comment]
@stan-sz Hello. This one should be overwritten if you set the base_url by `az cloud update`. I will get a test sub and test it again. 😄

**Comment by stan-sz** [comment]
Not necessarily. In these two places below the `ApplicationInsightsManagementClient` is initiated without the `base_url` so the default (public cloud base url) is used in the `__init__`:

https://github.com/Azure/azure-cli-extensions/blob/1148304a67206e71d1ebc37f24cac5a0700356b2/src/application-insights/azext_applicationinsights/_client_factory.py#L27-L35
