### ISSUE TITLE
az login fails with azure-ml-admin-cli extension

### ISSUE THREAD

**Issue by okhoma** [Azure/azure-cli-extensions#125]
### Extension name (the extension in question)
azure-ml-admin-cli (0.0.1)

### Description of issue (in as much detail as possible)
az login no longer works to login interactively after installing ML Server 9.3.0 with its CLI extension

```
PS C:\> az login
The behavior of this command has been altered by the following extension: azure-ml-admin-cli
login() missing 1 required positional argument: 'cmd'
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\knack\cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 347, in execute
    six.reraise(*sys.exc_info())
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 319, in execute
    result = cmd(params)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 180, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\knack\commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\__init__.py", line 420, in default_command_handler
    result = op(**command_args)
  File "C:\Users\labdsvm-admin\.azure\cliextensions\azure-ml-admin-cli\azext_admin\custom.py", line 88, in mls_login
    msi_port=msi_port)
TypeError: login() missing 1 required positional argument: 'cmd'
```

-----

---

### Environment summary

Install Method: MSI 
OS version: Windows Server 2016 Datacenter (DSVM) 
Shell Type: Powershell

```
PS C:\> az --version
azure-cli (2.0.30)

acr (2.0.22)
acs (2.0.30)
advisor (0.5.0)
appservice (0.1.30)
backup (1.1.0)
batch (3.1.11)
batchai (0.1.6)
billing (0.1.7)
cdn (0.0.13)
cloud (2.0.12)
cognitiveservices (0.1.11)
command-modules-nspkg (2.0.1)
configure (2.0.14)
consumption (0.2.2)
container (0.1.20)
core (2.0.30)
cosmosdb (0.1.19)
dla (0.0.18)
dls (0.0.20)
eventgrid (0.1.11)
eventhubs (0.1.1)
extension (0.0.11)
feedback (2.1.0)
find (0.2.8)
interactive (0.3.18)
iot (0.1.18)
keyvault (2.0.20)
lab (0.0.20)
monitor (0.1.4)
network (2.0.26)
nspkg (3.0.2)
profile (2.0.21)
rdbms (0.2.0)
redis (0.2.11)
reservations (0.1.1)
resource (2.0.26)
role (2.0.21)
servicebus (0.1.1)
servicefabric (0.0.11)
sql (2.0.24)
storage (2.0.30)
vm (2.0.29)

Extensions:
azure-ml-admin-cli (0.0.1)
dns (0.0.2)

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\labdsvm-admin\.azure\cliextensions'

Python (Windows) 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]

```
---

Reopened here based on comment in https://github.com/Azure/azure-cli/issues/5991

**Comment by swells** [comment]
This is a known issue. We fixed this on the latest DSVM deployments already and is resolved 
permanently going forward. 

To  resolve in the immediate, you can:

1.  If you don't need the admin extension you can remove it (and can always add it back in later w/o a MLServer reinstall)

2.  (or) Get our 9.3  whl patch that resolves this.

If you opt for **(1) above**, all you need to do is remove it, this should reinstate general `az login` functionality immediately.

Example form the command line:

```sh
az extension remove --name azure-ml-admin-cli
```

You can always add this az extension back in later if you installed MLServer. 

Example to re-add it:

```sh
az extension add --source '.\Program Files\Microsoft\ML Server\Setup\azure_ml_admin_cli-0.0.1-py2.py3-none-any.whl' --yes
```

If you opt for **(2) above**, please let me know and we can provide the new py-whl based off of the 9.3 release branch.

This is the same fix we already provided to the DSVM team.

**Comment by okhoma** [comment]
Thank you, @swells, it works on the newest DSVMs and it is enough for me to have a way to reinstall extensions

**Comment by RoelantStegmann** [comment]
Is there any option to have `az login` work directly after `az extension remove --name azure-ml-admin-cli
`? I still get the same error and have to launch a new terminal in order to make it work. This is a bit annoying since I work remotely so I have to ssh in again :)

**Comment by marabout2015** [comment]
@swells I just created a Ubuntu DSVM, and found this problem, so it is not fixed moving forward.

(py35) ~/Source/Repos/MLAKSDeployment
$ which az
/usr/bin/az
(py35) ~/Source/Repos/MLAKSDeployment
$ az login
The behavior of this command has been altered by the following extension: azure-ml-admin-cli
login() got an unexpected keyword argument 'msi'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 369, in execute
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 343, in execute
    result = cmd(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 182, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 436, in default_command_handler
    result = op(**command_args)
  File "/opt/az/extensions/azure-ml-admin-cli/azext_admin/custom.py", line 88, in mls_login
    msi_port=msi_port)
TypeError: login() got an unexpected keyword argument 'msi'

**Comment by marabout2015** [comment]
@RoelantStegmann I was recently told to remove the extension this way, and it seemed to work:
```
sudo -i az extension remove --name azure-ml-admin-cli
```

**Comment by tomconte** [comment]
Also got this problem today on a fresh DSVM.

**Comment by richajain44** [comment]
I also faced the similar issue, after removing azure-ml-admin-cli using sudo command as above, I get the following error: 
az ml account: 'account' is not in the az ml command group

**Comment by sqlshep** [comment]
Built DSVM yesterday, and i actually do need the ML Server installed, after the following error the PS console just hangs. 

az login --mls
az : WARNING: The behavior of this command has been altered by the following extension: azure-ml-admin-cli
At line:2 char:1
+ az login --mls
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (WARNING: The be...re-ml-admin-cli:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

**Comment by sqlshep** [comment]
I have downloaded and installed Machine Learning Server 9.3 on Windows 2016 and this problem still exists.  I need to login to the ML server to run diagnostics, and the first step is to run "az login --mls" which gives the following error below.  I do not see a resolution in this thread, what are the next steps? 

az : WARNING: The behavior of this command has been altered by the following extension: azure-ml-admin-cli
At line:1 char:1
+ az login --mls
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (WARNING: The be...re-ml-admin-cli:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
