### ISSUE TITLE
Azure CLI Extension Subscription Doesn't Support Azure Government Offer Types

### ISSUE THREAD

**Issue by JustinBacaAIS** [Azure/azure-cli-extensions#1733]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)

subscription

### Description of issue (in as much detail as possible)

Doesn't support the Azure Government Offer Type MS-AZR-USGOV-0017P

```
az --version
azure-cli                          2.6.0

command-modules-nspkg              2.0.3
core                               2.6.0
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
subscription                       0.1.3


az account create --enrollment-account-object-id <id> --offer-type "MS-AZR-USGOV-0017P" --display-name "DEMO-USGOV-SUB-01" --owner-object-id <id> --debug

az_command_data_logger : command args: account create --enrollment-account-object-id {} --offer-type {} --display-name {} --owner-object-id {} --debug
cli.azure.cli.core.parser : az account create: 'MS-AZR-USGOV-0017P' is not a valid value for '--offer-type'. See 'az account create --help'.
az account create: 'MS-AZR-USGOV-0017P' is not a valid value for '--offer-type'. See 'az account create --help'.
recommendation_provider: version: 2.6.0, command: account create, parameters: ['--enrollment-account-object-id', '--offer-type', '--display-name', '--owner-object-id', '--debug'], extension: subscription

The most similar choice to 'MS-AZR-USGOV-0017P' is:
        MS-AZR-0017P
```
-----

**Comment by yonzhan** [comment]
subscription

**Comment by anuragdalmia** [comment]
investigating.

**Comment by anuragdalmia** [comment]
We are in the process of updating our latest version of CLI SDK to fix this. The current target for this is end of July. We will keep this thread updated.

**Comment by anuragdalmia** [comment]
This has delayed because of some design changes that we had to undertake. New target for this is Aug 31.

**Comment by anuragdalmia** [comment]
Apologies for further delay here. We are shipping this as part of the GA version of the APIs ny 9/31.

**Comment by anuragdalmia** [comment]
@JustinBacaAIS We have released the latest version of our GA CLI SDK. You can find them at https://docs.microsoft.com/cli/azure/ext/account/account?view=azure-cli-latest&preserve-view=true. Resolving this issue. Please re-open if you run into issues.

**Comment by jamesseiwert** [comment]
We are still having this issue as of today with all of the latest updates

**Comment by anuragdalmia** [comment]
@jamesseiwert can you please share the latest issues that you are hitting.

**Comment by jamesseiwert** [comment]
![image](https://user-images.githubusercontent.com/31083794/120807238-59fe0b00-c50d-11eb-89e1-bfeb8516b88a.png)

**Comment by anuragdalmia** [comment]
You are still using the older APIs. With the latest release, there is a new subscription creation API called alias. https://docs.microsoft.com/en-us/azure/cost-management-billing/manage/programmatically-create-subscription-enterprise-agreement?tabs=azure-cli. We no longer need to take offer type as a parameter and will create a subscription based on your enrollment type automatically.
