### ISSUE TITLE
costmanagement : Invalid definition type 'AmortizedCost'; valid values: 'Usage'.

### ISSUE THREAD

**Issue by sshah90** [Azure/azure-cli-extensions#2021]
### Extension name

costmanagement

```
$ az version
{
  "azure-cli": "2.8.0",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.8.0",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {
    "costmanagement": "0.1.0"
  }
}
```

### Description of issue (in as much detail as possible)

I am running following command to create export job for `AmortizedCost`.

```
az costmanagement export create --name "exportTest" --type "AmortizedCost" --timeframe "WeekToDate" --storage-container="export" --storage-account-id="/subscriptions/XXXX/resourceGroups/XXXXX/providers/Microsoft.Storage/storageAccounts/XXXX" --storage-directory="test" --scope "/subscriptions/XXXX/"
```

But I am getting following error

```
cli.azure.cli.core.util : (400) Request properties validation failed: Invalid definition type 'AmortizedCost'; valid values: 'Usage'.
 (Request ID: 389bfa8d-033c-44a8-8a46-00f99a98a1fa)
(400) Request properties validation failed: Invalid definition type 'AmortizedCost'; valid values: 'Usage'.
 (Request ID: 389bfa8d-033c-44a8-8a46-00f99a98a1fa)
````

Can someone help here, please?

**Comment by yonzhan** [comment]
add to S174

**Comment by fl-max** [comment]
Does not appear to work with the REST API either:

**export_sub.json**
```json
{
    "properties": {
      "schedule": {
        "status": "Active",
        "recurrence": "Weekly",
        "recurrencePeriod": {
          "from": "2020-07-14T00:00:00Z",
          "to": "2020-07-16T00:00:00Z"
        }
      },
      "format": "Csv",
      "deliveryInfo": {
        "destination": {
          "resourceId": "/subscriptions/${SUBSCRIPTION_ID}/resourceGroups/${RG_NAME}/providers/Microsoft.Storage/storageAccounts/${SA_NAME}",
          "container": "test",
          "rootFolderPath": "amortized"
        }
      },
      "definition": {
        "type": "AmortizedCost",
        "timeframe": "MonthToDate",
        "dataset": {
          "granularity": "Daily"
        }
      }
    }
  }
```

**Command:**
```bash
URL="https://management.azure.com/subscriptions/${SUBSCRIPTION_ID}/providers/Microsoft.CostManagement/exports/TestExport?api-version=2019-11-01"
az rest -m put -u ${URL} --body @export_sub.json
```

**Result:**
```bash
Bad Request({"error":{"code":"400","message":"Request properties validation failed: Invalid definition type 'AmortizedCost'; valid values: 'Usage'.\r\n (Request ID: 00000000-0000-0000-0000-0000000000)"}})
```

All documentation seem to suggest this works for both the [azure-cli](https://docs.microsoft.com/en-us/cli/azure/ext/costmanagement/costmanagement/export?view=azure-cli-latest#ext-costmanagement-az-costmanagement-export-create-optional-parameters) and [REST API](https://docs.microsoft.com/en-us/rest/api/cost-management/exports/createorupdate#exporttype).

**Comment by yonzhan** [comment]
@fl-max service team should look into this.

**Comment by fl-max** [comment]
This seems to be fixed in API Version `2020-06-01`

Changing the `api_version` [here](https://github.com/Azure/azure-cli-extensions/blob/master/src/costmanagement/azext_costmanagement/vendored_sdks/costmanagement/operations/_export_operations.py#L266) worked for me with the exception of having to add the `--recurrence-period` flag to OP's command. 

I see the `api_version` is statically set in a bunch of class (by design?); should be updated in all classes?

**Comment by kolbyrax** [comment]
Also running into this attempting to create an export through the portal (as well as az cli) in government cloud.  Works fine through the portal and az cli in commercial.

**Comment by haroldrandom** [comment]
Last time we generate CostManagement SDK based on API 2019-11-01. Any change since then?
Could you post swagger here? We might need to upgrade SDK from CostManagement and generate newer SDK for it.

**Comment by kolbyrax** [comment]
I don't have swagger, will look into it...but from firefox's web tools you can see the Government portal is trying to hit the 2019-11-01 api

https://management.usgovcloudapi.net/providers/Microsoft.Billing/billingAccounts/XXXXXX/providers/Microsoft.CostManagement/query?api-version=2019-11-01&$top=2500

while the Commercial portal is going to api 2020-06-01

https://management.azure.com/providers/Microsoft.Billing/billingAccounts/XXXXXX/providers/Microsoft.CostManagement/exports?api-version=2020-06-01&$expand=runHistory&_=1600785437399

**Comment by melmullen** [comment]
This should be fixed now. Please retry.

**Comment by kolbyrax** [comment]
I can create the export now (through the Gov portal), but when it runs it fails immediately:
 
“Cost Management RP was not registered with the subscription under customer's tenant.”
 
However the Cost Management resource provider is registered in all the subscriptions for this tenant.  Also the Cost Management Export resource provider is registered for the subscription that has the storage account I want to send the export to.
 
I tried unregistering the Cost Management Export resource provider and re-registering it then manually running the export, but it fails to run almost immediately.

**Comment by melmullen** [comment]
> I can create the export now (through the Gov portal), but when it runs it fails immediately:
> 
> “Cost Management RP was not registered with the subscription under customer's tenant.”
> 
> However the Cost Management resource provider is registered in all the subscriptions for this tenant. Also the Cost Management Export resource provider is registered for the subscription that has the storage account I want to send the export to.
> 
> I tried unregistering the Cost Management Export resource provider and re-registering it then manually running the export, but it fails to run almost immediately.

Have you already reported this through another channel? 

Note that the tenant under which you are logged into the portal must be the same as the storage subscription's tenant. You can check this by clicking "?" on the top right of the portal page and selecting "Show Diagnostics". This option provides a JSON file with a "security/user" section and a "subscriptions" section. You can check that the appropriate "tenantId" values are equal.

**Comment by kolbyrax** [comment]
I opened a case with Billing Support, lmk if you want the case number.

**Comment by melmullen** [comment]
I believe this was addressed back in October. Please close the ticket if you concur.

**Comment by lgerd** [comment]
@kolbyrax  How as Billing Support able to resolve the issue? I am also getting “Cost Management RP was not registered with the subscription under customer's tenant”, but everything is in the same tenant.

**Comment by mikeeq** [comment]
Hi All,

It still doesn't work for me (I guess It's due to not updated version of API in python code for this extension), any suggestions?
```
az costmanagement export create --name "$REPORT_NAME" --type ActualCost \
--scope "subscriptions/$CURRENT_SUBSCRIPTION_ID" --storage-account-id "${STORAGE_ACCOUNT_ID}" \
--storage-container "$STORAGE_CONTAINER" --timeframe MonthToDate --recurrence Daily \
--recurrence-period from="$START_DATE" to="$END_DATE" \
--schedule-status Active --storage-directory "$STORAGE_DIR" 

(400) Request properties validation failed: Invalid definition type 'ActualCost'; valid values: 'Usage'.
```

```
➜ az version                                                         
{
  "azure-cli": "2.28.1",
  "azure-cli-core": "2.28.1",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "aks-preview": "0.5.19",
    "azure-devops": "0.18.0",
    "costmanagement": "0.1.1"
  }
}
```

**Comment by vighneshpp1986** [comment]
> Hi All,
> 
> It still doesn't work for me (I guess It's due to not updated version of API in python code for this extension), any suggestions?
> 
> ```
> az costmanagement export create --name "$REPORT_NAME" --type ActualCost \
> --scope "subscriptions/$CURRENT_SUBSCRIPTION_ID" --storage-account-id "${STORAGE_ACCOUNT_ID}" \
> --storage-container "$STORAGE_CONTAINER" --timeframe MonthToDate --recurrence Daily \
> --recurrence-period from="$START_DATE" to="$END_DATE" \
> --schedule-status Active --storage-directory "$STORAGE_DIR" 
> 
> (400) Request properties validation failed: Invalid definition type 'ActualCost'; valid values: 'Usage'.
> ```
> 
> ```
> ➜ az version                                                         
> {
>   "azure-cli": "2.28.1",
>   "azure-cli-core": "2.28.1",
>   "azure-cli-telemetry": "1.0.6",
>   "extensions": {
>     "aks-preview": "0.5.19",
>     "azure-devops": "0.18.0",
>     "costmanagement": "0.1.1"
>   }
> }
> ```

Same issue for me

(400) Request properties validation failed: Invalid definition type 'ActualCost'; valid values: 'Usage'.

**Comment by jsntcy** [comment]
The ETA for the fix will be the end of March if there is no block issue from service side.

**Comment by jsntcy** [comment]
@mikeeq , @vighneshpp1986, @fl-max, @sshah90 

The fix has been released in costmanagement 0.2.1 (latest version), please [upgrade ](https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-overview#how-to-update-extensions) to the latest version to have a try.

BTW, please also note there are some [breaking changes](https://github.com/Azure/azure-cli-extensions/blob/main/src/costmanagement/HISTORY.rst#021) in 0.2.1, you may need some changes in your scripts if your scripts are impacted by those breaking changes.

**Comment by Praveen-Mariyappa** [comment]
This issue is still not resolved. I am on the last costmanagement version 0.2.1 and I am still getting the error message.

PS D:\Cost> az extension update --name costmanagement
Latest version of 'costmanagement' is already installed.
Use --debug for more information

PS D:\Cost> az costmanagement export create --name $CLUSTER_NAME --scope "/subscriptions/$CLUSTER_SUBSCRIPTION_ID/resourceGroups/$MC_RESOURCE_GROUP" --timeframe=MonthToDate --type AmortizedCost --recurrence-period "from=$FROM_DATE" 'to=2200-01-01T00:00:00' --recurrence=Daily --schedule-status=Active --storage-account-id "/subscriptions/$STORAGE_SUBSCRIPTION_ID/resourceGroups/$STORAGE_ACCOUNT_RESOURCE_GROUP/providers/Microsoft.Storage/storageAccounts/$STORAGE_ACCOUNT_NAME" --storage-container cost


(400) Request properties validation failed: Invalid definition type 'AmortizedCost'; valid values: 'Usage'.
 (Request ID: a3940386-04b7-4723-8d52-e5d7ff7b7286)
Code: 400
Message: Request properties validation failed: Invalid definition type 'AmortizedCost'; valid values: 'Usage'.
 (Request ID: a3940386-04b7-4723-8d52-e5d7ff7b7286)

**Comment by quannhoang** [comment]
I still have the same issue when using Terraform automate creating cost report export. Does anyone know any workaround for this one?
```│ Error: updating Scoped Export (Scope: "/subscriptions/d53028c1-2dd1-47c8-bb20-8eb1f5ea9338"
│ Export Name: "myexport"): exports.ExportsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="400" Message="Request properties validation failed: Invalid definition type 'ActualCost'; valid values: 'Usage'.\r\n (Request ID: 399323f0-d1af-4fc4-928e-f729645e2f15)"
│ 
│   with azurerm_subscription_cost_management_export.daily_cost_export,
│   on azure.tf line 48, in resource "azurerm_subscription_cost_management_export" "daily_cost_export":
│   48: resource "azurerm_subscription_cost_management_export" "daily_cost_export" {
│ 
│ updating Scoped Export (Scope: "/subscriptions/d53028c1-2dd1-47c8-bb20-8eb1f5ea9338"
│ Export Name: "myexport"): exports.ExportsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error.
│ Status=400 Code="400" Message="Request properties validation failed: Invalid definition type 'ActualCost'; valid values: 'Usage'.\r\n (Request ID:
│ 399323f0-d1af-4fc4-928e-f729645e2f15)"

**Comment by zioproto** [comment]
@yonzhan can we open this issue again ? it seems it is not solved

**Comment by zioproto** [comment]
I am able to reproduce the issue:
```
% az extension show --name costmanagement
ExtensionType    Name            Path                                                     Version
---------------  --------------  -------------------------------------------------------  ---------
whl              costmanagement  /Users/saverioproto/.azure/cliextensions/costmanagement  0.2.1
```

Repro step:

```
az costmanagement export create --name kubecostexport --scope "/subscriptions/xxxxxxxx-2222-3333-4444-xxxxxxxxxxxx"   --storage-account-id "/subscriptions/xxxxxxxx-2222-3333-4444-xxxxxxxxxxxx/resourceGroups/kubecost/providers/Microsoft.Storage/storageAccounts/xxxxxxxxftademo"   --storage-container kubecost --timeframe MonthToDate   --recurrence Daily --recurrence-period from=$(date +"%Y-%m-%dT%H:%M:%S") to=2024-01-17T11:09:12 --storage-directory  cur --type AmortizedCost  --schedule-status "Active"

(400) Request properties validation failed: Invalid definition type 'AmortizedCost'; valid values: 'Usage'.
 (Request ID: 07261553-9813-4637-b0a4-d08e853ec489)
Code: 400
Message: Request properties validation failed: Invalid definition type 'AmortizedCost'; valid values: 'Usage'.
 (Request ID: 07261553-9813-4637-b0a4-d08e853ec489)
 ```

**Comment by jsntcy** [comment]
@adwise3, do you know if this error is because customers use improper subscription type?

**Comment by zioproto** [comment]
@jsntcy when I try to create the Cost Export with the Azure Portal, in the Export Details, I **dont** have a "Metric" like I see here:
https://learn.microsoft.com/en-us/azure/cost-management-billing/costs/media/tutorial-export-acm-data/basics_exports.png

Does it mean it is a subscription type problem ?

**Comment by zioproto** [comment]
@quannhoang I figured out the problem was that my subscription was PAYG (Pay as you go). In this case `AmortizedCost` is not supported and the only valid value is `Usage`.

Reference:
https://learn.microsoft.com/en-us/azure/cost-management-billing/reservations/reservation-amortization#view-amortized-costs

<img width="863" alt="Screenshot 2023-01-18 at 12 53 21" src="https://user-images.githubusercontent.com/789701/213164857-8ba3ad78-1eb8-4b95-a83d-4d81ca989133.png">
