### ISSUE TITLE
`containerapp compose create` is not respecting the --location argument

### ISSUE THREAD

**Issue by charris-msft** [Azure/azure-cli-extensions#5252]
### Related command
`az containerapp compose create`

### Extension name (the extension in question)
containerapp-compose

### Description of issue (in as much detail as possible)
When running the command and specifying a location via `-l` or `--location` it ignores the specified location and defaults to 'westus3' which "is not currently supported".

![image](https://user-images.githubusercontent.com/74415662/185413876-6d568017-c3b1-4e44-a72f-3b6412e85c98.png)

That value is not coming from my param-persist either:
![image](https://user-images.githubusercontent.com/74415662/185414051-a760bf55-fb61-4332-9405-c1e5ec00dd26.png)

-----

**Comment by yonzhan** [comment]
route to CXP team

**Comment by smurawski** [comment]
@charris-msft What versions of the extensions (containerapp and containerapp-compose) do you have installed?

**Comment by charris-msft** [comment]
@smurawski 
```
Name                  Path                                                        Preview    Version
--------------------  ----------------------------------------------------------  ---------  ---------
containerapp          C:\Users\charris\.azure\cliextensions\containerapp          True       0.3.9
containerapp-compose  C:\Users\charris\.azure\cliextensions\containerapp-compose  True       0.2.0
```

**Comment by smurawski** [comment]
@charris-msft 

I'm finding another bug in the 0.3.9 that has blocked me from testing so far ( https://github.com/Azure/azure-cli-extensions/issues/5253 ) , but I was able to deploy successfully to Canada Central with the `containerapp` extension at 0.3.8 and 0.3.7.

I'll continue to check with 0.3.9 with a private image shortly.

**Comment by smurawski** [comment]
@charris-msft 

I've confirmed your problem - it appears that the resource group location is overriding command line provided location arguments - which appears to be happening regardless of containerapp extension version.  I'll investigate further.

**Comment by charris-msft** [comment]
@smurawski I tested by moving my existing resources to a new rg in the location where I wanted to create the new containerapp, ran the command and it didn't error out this time. (still running)

**Comment by smurawski** [comment]
This is fixed in https://github.com/Azure/azure-cli-extensions/pull/5262 (version 0.2.1) which is available now.

**Comment by charris-msft** [comment]
Looks like it's working - it created the ACA Environment in the correct location. 

Though because I'm still getting prompted my registry credentials (which I don't know), I can't confirm that the ACA gets created in the correct location as well.

**Comment by smurawski** [comment]
Thanks @charris-msft !  The registry credentials prompting should be fixed once v0.3.10 of the `containerapp` extension ships.

The PR for that is here - https://github.com/Azure/azure-cli-extensions/pull/5241

**Comment by RakeshMohanMSFT** [comment]
@charris-msft and @smurawski can we close this issue, i see that the PR is merged.

**Comment by charris-msft** [comment]
I did some more testing and I'm comfortable closing it.
