### ISSUE TITLE
`az containerapp update --yaml` is not setting minreplicas to 0

### ISSUE THREAD

**Issue by charris-msft** [Azure/azure-cli-extensions#5391]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Related command
`containerapp update`

### Extension name (the extension in question)
containerapp

### Description of issue (in as much detail as possible)
I originally created a containerapp with a yaml file that specified `minReplicas: 0`

Now, I want to update minReplicas to 0 so I updated the yaml file like this:
```
    scale:
      minReplicas: 0
      maxReplicas: 1
```

 and ran

`az container app update ... --yaml updated.yaml`

However, in the output from the command and in the portal, the minReplicas is still set to 0.

-----

**Comment by yonzhan** [comment]
route to CXP team

**Comment by panchagnula** [comment]
@charris-msft thanks for reporting, we will investigate further. However, wanted to get a clarification, if this behavior is specific to yaml from CLI command. Does this work with ARM template or updating from portal directly? 
Thanks. @StrawnSC , @haroonf FYI.

**Comment by charris-msft** [comment]
@panchagnula - 
I saw the issue with yaml from CLI and with the --min-replicas parameter from CLI (no --yaml specified).
It behaved as expected when I updated in the portal.
I did not try with an ARM template.

**Comment by panchagnula** [comment]
> @panchagnula -
> I saw the issue with yaml from CLI and with the --min-replicas parameter from CLI (no --yaml specified).
> It behaved as expected when I updated in the portal.
> I did not try with an ARM template.

Gotcha. Could you also provide the CLI version being used (run az --version).  CLI updated recently to use the latest api-version, so I am wondering if there is a change here we need to look into. Portal still uses an older api-version. Thanks!

**Comment by charris-msft** [comment]
```
 >  az --version
azure-cli                         2.40.0

core                              2.40.0
telemetry                          1.0.8

Extensions:
connectedk8s                       1.3.3
containerapp                      0.3.11
customlocation                     0.1.3
k8s-extension                      1.3.4
rdbms-connect                      1.0.3

Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\chris\.azure\cliextensions'

Python (Windows) 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 15:58:59) [MSC v.1929 32 bit (Intel)]
```

**Comment by stfnzl** [comment]
Had same issue but got around it by providing --max-replicas as well

**Comment by Greedygre** [comment]
Hi @charris-msft @jason-berk-k1x 
This issue about `az containerapp update --min-replicas 0` not work has been fixed and released in version `0.3.46` of `containerapp` extension.
You can update the extension with command, thanks!

```
az extension add -n containerapp --upgrade
```

About setting `minReplicas` to 0 in `--yaml` not work, the fix PR has been merged, it will be released in azure-cli `2.56.0` in January.

**Comment by Mortana89** [comment]
I see this is still an issue when we deploy our bicep via AZDO.
Using AzureResourceManagerTemplateDeployment and the latest bicep version resource symbolicname 'Microsoft.App/containerApps@2024-10-02-preview' = 

minReplica is not updating...

**Comment by Greedygre** [comment]
> I see this is still an issue when we deploy our bicep via AZDO. Using AzureResourceManagerTemplateDeployment and the latest bicep version resource symbolicname 'Microsoft.App/containerApps@2024-10-02-preview' =
> 
> minReplica is not updating...

@Mortana89 
I cannot repro this with 'Microsoft.App/containerApps@2024-10-02-preview'  with following template.
```
resource containerApp 'Microsoft.App/containerApps@2024-10-02-preview' = {
  name: containerAppName
  location: region
  tags: tags
  identity: {
    type: 'UserAssigned'
    userAssignedIdentities: {
      '${commonIdentity.id}': {}
    }
  }
  properties: {
    environmentId: environment.id
    workloadProfileName: empty(workloadProfile) ? null : workloadProfile
    configuration: {
      activeRevisionsMode: revisionMode
      ingress: {
        external: ingressExternal
        transport: 'auto'
        targetPort: 5000
      }
      registries: [
        {
          identity: commonIdentity.id
          server: containerRegistryServer
        }
      ]
    }
    template: {
      containers: [
        {
          name: 'maincontainer'
          image: '${containerRegistryServer}/httptestapp:${containerImageVersion}'
          resources: {
            #disable-next-line BCP036
            cpu: '0.5'
            memory: '1Gi'
          }
        }
      ]
      scale: {
        minReplicas: 0
        maxReplicas: 3
      }
    }
  }
}
```
Can you give the template you used? And the containerapp name and the region and the date you occur this issue to me? 
What is the behavior you think the minReplica is not updating? 

About check the minReplica, you can use command: `az containerapp show -n {your-containerapp-name} -g {rg-name} --query "properties.template.scale.minReplicas"`

**Comment by Mortana89** [comment]
Above command shows me '1'. 
Did you first create the aca with 1 as minreplica? Because that's what we did. Only to later try to change it to 0 because of scaling rules.

Our bicep (minReplica is a param that is set to 0 hardcoded):
`resource containerApp 'Microsoft.App/containerApps@2024-10-02-preview' = {
  name: '${environment}-${locationCap}-${containerAppName}'
  location: location
  identity: {
    type: 'UserAssigned'
    userAssignedIdentities: {
      '${userIdentity.id}': {}
    }
  }
  properties: {
    managedEnvironmentId: containerEnvironmentId
    workloadProfileName: 'consumption'
    configuration: {
      activeRevisionsMode: 'Single'
      ingress: {
        external: enableIngress
        targetPort: 8080
        allowInsecure: false
        traffic: [
          {
            latestRevision: true
            weight: 100
          }
        ]
      }
      maxInactiveRevisions: 1
      registries: [
        {
          server: '${acrUrl}.azurecr.io'
          identity: userIdentity.id
        }
      ]
      secrets: [
        {
          keyVaultUrl: '${keyvaultUrl}secrets/ServiceBus-QueueConnectionString'
          identity: userIdentity.id
          name: 'asb-connectionstring'
        }
      ]
    }
    template: {
      revisionSuffix: replace(revisionSuffix, '.', '-')
      scale: {        
        cooldownPeriod: 120
        pollingInterval: 60        
        minReplicas: minReplica
        maxReplicas: maxReplica
        rules: allScalingRules     
      }
      terminationGracePeriodSeconds: 120
      containers: [
        {
          probes: [
            {
              type: 'Readiness'
              httpGet: {
                port: 8080
                path: 'health'
                scheme: 'HTTP'
              }
              initialDelaySeconds: 15
              periodSeconds: 3
            }
          ]
          name: '${containerAppName}-container'
          image: containerAppImage
          env: [
            {
              name: 'ASPNETCORE_ENVIRONMENT'
              value: ASPNETENV
            }
            {
              name: 'ASPNETCORE_ConnectionStrings__secrets'
              value: keyvaultUrl
            }
            {
              name: 'AZURE_CLIENT_ID'
              value: userIdentity.properties.clientId
            }
            {
              name: 'DD_SERVICE'
              value: containerAppName
            }
            {
              name: 'DD_VERSION'
              value: revisionSuffix
            }
          ]
          resources: {
            cpu: allocatedCpu
            memory: maxMem
          }
        }
      ]
    }
  }
}`

**Comment by Greedygre** [comment]
> Did you first create the aca with 1 as minreplica? Because that's what we did. Only to later try to change it to 0 because of scaling rules.

@Mortana89 

Yes, I set the minReplica to 3 first, then update it to `0`. It works fine.

Base on the template you give, I think you should check what is the value of `minReplica` in your template.

Besides, you can have a try with set the value of `minReplica` to 0 directly as following to do a test:
```
scale: {
        minReplicas: 0
        maxReplicas: 3
      }
```

**Comment by Mortana89** [comment]
Stupid, it was indeed a setting being overridden on a higher scope, apologies! It works now, thanks!

**Comment by yanghoxom** [comment]
for someone stuck with azure automation account like me
we also need run
```
az extension add -n containerapp --upgrade
```
before call
```
--min-replicas 0
```
